name: "Publish Code Coverage Results on Sonar Cloud"
on:   # Triggers the workflow on push or pull request events
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  SonarTrigger:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build simple java app with maven
        run: mvn -B package --file pom.xml

      - name: Publish Sonar Scan Result on SonarCloud.io
        uses: asalan316/sonarcloud-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}